
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

////SHIFT + F6


////Pertama Import 
////1.java io File              ->setting file
////2.java io FileInput Stream  ->setting file
////3.java io Input Stream      ->setting file
////4.java util Calendar        ->setting waktu 
////5.javax swing JFile Chooser ->setting file
////6.javax swing JOptionPane   ->windows pop up
////7.sun audio AudioPlayer     ->audioplayer
////8.sun audio AudioStream     ->audioplayer





public class alarm extends javax.swing.JFrame {

    /**
     * Creates new form alarm
     */
    public alarm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jammm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        vpath = new javax.swing.JLabel();
        vjam = new javax.swing.JTextField();
        vket = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reminder's Note");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jammm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jammm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jammm.setText("REMINDER'S NOTE");
        jammm.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jammmPropertyChange(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jCheckBox1.setText("Aktif");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Suara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vpath.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        vpath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vpath.setText("File Url");
        vpath.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        vjam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vjam.setText("00:00:00");
        vjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vjamActionPerformed(evt);
            }
        });

        vket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vketActionPerformed(evt);
            }
        });

        jLabel1.setText("Keterangan :");

        jLabel2.setText("Set Alarm :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(vjam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(vpath, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(vket, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jCheckBox1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(7, 7, 7)
                .addComponent(vpath, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jammm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jammm, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(376, 264));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
 /////2.Setting Pengaturan Jam sesuai laptop
    
      private void jam() {
          ActionListener taskPerformer=new ActionListener(){ ////klik ALT+ENTER -> import ActionListener ->TOP
             
            public void actionPerformed(ActionEvent evt){ ////klik ALT+ENTER -> import actionPerformed ->TOP
                String nol_bulan="";
                String nol_hari="";
                String nol_jam="";
                String nol_menit="";
                String nol_detik="";
                Calendar dt=Calendar.getInstance(); ////untuk mengambil informasi waktu
 
                int nilai_jam=dt.get(Calendar.HOUR_OF_DAY);         ////3.Calendar.HOUR_OF_DAY digunakan untuk settingan jam
                int nilai_menit=dt.get(Calendar.MINUTE);            ////4.Calendar.MINUTE digunakan untuk settingan menit
                int nilai_detik=dt.get(Calendar.SECOND);            ////5.Calendar.SECOND digunakan untuk settingan detik
                
               
                if(nilai_jam<=9){
                    nol_jam="0";
                }
                if(nilai_menit<=9){
                    nol_menit="0";
                }
                if(nilai_detik<=9){
                    nol_detik="0";
                }
                
                String jam=nol_jam+Integer.toString(nilai_jam);
                String menit=nol_menit+Integer.toString(nilai_menit);
                String detik=nol_detik+Integer.toString(nilai_detik);
              jammm.setText(jam+":"+menit+":"+detik);              ////6.Label dengan variabel "jammm" akan berubah sesuai settingan jam menit dan detik

            }
            };
            new javax.swing.Timer(1000,taskPerformer).start(); ////untuk start
    }
    
    
////7.Untuk inputan file yang nantinya akan digunakan ringtone reminder
      
    void player(){
        InputStream in; ////apabila merah -> ALT+ENTER ->input stream ->TOP
        try {   ////try {}catch(Exception e){}
            in = new FileInputStream(new File(vpath.getText()));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            e.printStackTrace();
        }            
    }
    
    
 ////8.Untuk mengkondisikan apabila button "Suara" di klik
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser chooser = new JFileChooser(); ////apabila merah -> ALT+ENTER -> j file chooser -> TOP
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        vpath.setText(filename);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
////9.Untuk memunculkan Pop-Up welcome ketika aplikasi pertama kali dijalankan    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jam(); 
JOptionPane.showMessageDialog(rootPane, "Welcome to REMINDER'S NOTE");
        
    }//GEN-LAST:event_formWindowOpened

    
////10.Untuk mengkondisikan ketika checkbox aktif di pilih
    private void jammmPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jammmPropertyChange
        
        if (jCheckBox1.isSelected()==true) {    ////apabila checkbox di pilih maka textfield dengan variable "vket & vjam" tidak dapat di edit
            vket.setEnabled(false);
            vjam.setEnabled(false);
            if (vjam.getText().equals(jammm.getText())) {
                player();
                JOptionPane.showMessageDialog(rootPane, ""+vket.getText()+"");
            }else{
            }
            
        }else{
            vket.setEnabled(true);  ////apabila checkbox tidak di pilih maka textfield dengan variable "vket & vjam" dapat di edit
            vjam.setEnabled(true);
        }
        
    }//GEN-LAST:event_jammmPropertyChange

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void vjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vjamActionPerformed

    private void vketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alarm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jammm;
    private javax.swing.JTextField vjam;
    private javax.swing.JTextField vket;
    private javax.swing.JLabel vpath;
    // End of variables declaration//GEN-END:variables
}
